Implement basic canvas drawing functionality
Giga-Chad-LLC/Enchanted-Towers pull request #5
Opened 2023-03-05 16:02 UTC by dmitrii-artuhov

В этой ветке из функционала:
- Очистка всего канваса
- Смена цветов

Переделал архитектуру в соответствии с тем, как обсуждали на прошлом созвоне

2023-03-05 16:09 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/components/enchantment/EnchantmentBook.java
> +    static ArrayList <PointF> circle = new ArrayList<>(Arrays.asList(
Обычно такое в конфиг-файлах делают. Либо поправь здесь, либо тикет заведи

2023-03-05 17:31 UTC, Vladislav0Art requested changes

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasEnchantment.java
> +        float[] points = enchantment.points;
Лучше сделать через getter, чем лезть во внутренности структуры.

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasEnchantment.java
> +        newPath.moveTo(points[0], points[1]);
Сейчас класс `CanvasEnchantment` зависит от того, как хранятся points внутри `Enchantments` (есть хрупкое предположение, что точки идут `x_0, y_0, x_1, y_1, ...`). Лучше делать получение каждой точки через что-то по типу метода `getPoint(index)`, который вернет какой-нибудь класс `CanvasPoint` с полями `x`, `y` и их геттерами.

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasEnchantment.java
> +        brush.setColor(color);
Что делает `brush` в данной функции и что такое `setColor` для нее?

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasFragment.java
> +        currentCanvasBrushColor++;
`currentCanvasBrushColor = (currentCanvasBrushColor + 1) % brushColors.length`?

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasFragment.java
> +        int changeColorButtonId = getResources().getIdentifier("changeColorButton", "id", getContext().getPackageName());
Этот метод 2 раза применяется, его можно вынести в `private` функцию `registerOnClickActionOnView(String buttonId, Callable action)`, чтобы не дублировать снова, если у тебя какие-то еще кнопки на canvas'е появятся.

@vvselischev, как считаешь, подойдет ли такой подход тут или overkill?

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasWidget.java
> +    @Override
Не понятно, что такое переменная `result` и за что она отвечает в случае `true/false`.

2023-03-05 17:31 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/interactors/canvas/CanvasDrawEnchantmentInteractor.java
> +    public boolean onTouchEvent(CanvasState state, float x, float y, int motionEventType) {
Вопрос (изменений в коде не требуется):
Данный метод возвращает `true`, если `interactor` что-то делал и `false` иначе?

2023-03-05 17:37 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/components/enchantment/Enchantment.java
> +    public final float[] points;
Может два массива сделаем? Или заведём структуру Point -- обёртку над парой координат?

2023-03-05 17:38 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasFragment.java
> +        currentCanvasBrushColor++;
Можно и так оставить, процент так себе читается

2023-03-05 17:39 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/components/canvas/CanvasEnchantment.java
> +        newPath.moveTo(points[0], points[1]);
+1

2023-03-05 17:39 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/MainActivity.java
> +//        /*StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder(StrictMode.getVmPolicy())
Этот код нужен или можно его не коммитить?

2023-03-12 23:03 UTC, vvselischev commented on client/app/src/main/java/enchantedtowers/client/MainActivity.java
> +//        /*StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder(StrictMode.getVmPolicy())
И всё-таки

2023-03-12 23:03 UTC, vvselischev approved these changes

2023-03-13 13:04 UTC, Vladislav0Art approved these changes

2023-03-13 13:04 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/MainActivity.java
> +        if (view instanceof Button && ((Button)view).getId() == R.id.changeToCanvasActivity) {
Обязателен ли каст к `Button`? у `view` нет метода `getId()`? Кажется, что такой метод довольно общий и должен быть у `View` тоже

2023-03-13 20:16 UTC, merged