Adding basic functionality to work with google maps
Giga-Chad-LLC/Enchanted-Towers pull request #6
Opened 2023-03-10 11:48 UTC by dezd4r

Есть несколько проблем: 

1. Если приложению не дать разрешения на изпользование геолокации или дать, но навсегда, оно перестанет запускаться или вовсе вылетит, надо будет включать GPS после разрешения на его использование(это не сделано).
2. Зона действия игрока отрисовывается единожды, но это решается отдельным поток, который раз  внесколько секунду будет просить координаты игрока и по ним все перерисовывать.

2023-03-12 20:57 UTC, dmitrii-artuhov commented
Из замечаний не относящихся к коду:
- наверное, стоит заменить стиль для карты, так как на этой не видно подписей населенных пунктов, так как текст сливается с задним фоном (можно [этот](https://snazzymaps.com/style/50689/old-time-fantasy) попробовать) 
- на моем телефоне не появлялась кнопка геолокации (то есть я не мог свою позицию посмотреть), пока я не переоткрыл приложение

2023-03-12 22:15 UTC, dmitrii-artuhov requested changes

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        //Toast.makeText(this, "Please turn on GPS", Toast.LENGTH_SHORT).show();
если комментарии не нужны, то лучше их убрать совсем

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +public class MapsActivity extends AppCompatActivity
лучше везде переименовать на `MapActivity`, в том числе и имена файлов

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +                == PackageManager.PERMISSION_GRANTED*/) {
аналогично про комментарии

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        //Toast.makeText(this, "Please turn on GPS", Toast.LENGTH_SHORT).show();
аналогично про комментарии

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +    Location location;
`private Location location;`

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACC
вот эти проверки `checkSelfPermission(...) == ...` часто повторяются. Лучше вынести в отдельный метод и как-то унифицировать.

2023-03-12 22:15 UTC, dmitrii-artuhov commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        if (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION)
то же самое - про повторение кода для проверки прав доступа

2023-03-14 10:31 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +    public void onMapReady(@NonNull GoogleMap googleMap) {
Длинный метод, надо разбить на маленькие логические куски.

2023-03-14 10:32 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        assert mapFragment != null;
Лучше выкинуть ошибку, ассерты в продакшене не используются

2023-03-14 10:33 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +                    //Nothing
А зачем её оверрайдить тогда?

2023-03-14 10:34 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, locationListener);
Что такое 0, 0? Лучше оставить комментарий или сделать константу

2023-03-14 10:34 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +public class MapsActivity extends AppCompatActivity
+1

2023-03-14 10:41 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        CircleOptions circleOptions = new CircleOptions();
Этот объект всегда константный? Если да, то, может, лучше не создавать каждый раз, а сделать полем и инициализировать там же, а тут просто его подвинуть. CircleOptions реализует шаблон Builder, поэтому можно писать просто:
```
new CircleOptions()
  .strokeColor(radius)
  .fillColor(...)
  .strokeWidth(...)
```

2023-03-14 10:43 UTC, vvselishchev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +            enableMyLocation();
Просто интересно, что будет с этим циклом, если разрешение долго не дают? Есть ли внутри какой-то sleep между итерациями? Что будет, если вывести через Toast что-нибудь внутри цикла?

2023-03-14 10:58 UTC, Vladislav0Art commented
Нужно текущие изменения в папке `app/` переложить в папку `client/app` (`app/build.gradle` нужно поместить либо в `client/app/build.gradle`, либо в `build-logic/android-application/build.gradle` или в папку `build-logic/android-application/src` - там есть gradle-файл).

2023-03-18 13:05 UTC, Vladislav0Art requested changes

2023-03-18 13:05 UTC, Vladislav0Art commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +            enableMyLocation();
Возможно, запрос прав правильнее делать через event'ы, чтобы таким aka `while(true)` (если `enableMyLocation` неблокирующий) не убивать CPU. 

Особо сильно не вникал, как это правильно делать, но у `ActivityCompat` есть interface [`ActivityCompat.OnRequestPermissionsResultCallback`](https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback), от которого можно отнаследоваться и при получении доступа прав создавать нужный activity.

У Android есть репозиторий с тем, как это правильно делать: [permissions-samples](https://github.com/android/permissions-samples). Наш случай, скорее всего [permissions-samples/RuntimePermissionsBasic](https://github.com/android/permissions-samples/tree/c4573f1218cef81295b519592718ecef3b144095/RuntimePermissionsBasic). 

Если в данном примере посмотреть в [`MainActivity.java`](https://github.com/android/permissions-samples/blob/c4573f1218cef81295b519592718ecef3b144095/RuntimePermissionsBasic/Application/src/main/java/com/example/android/basicpermissions/MainActivity.java#L100), то у него, как я понял, такой workflow:

1. Создать кнопку для показа камеры.
2. При нажатии, если права уже есть, то показать камеру, иначе - сделать запрос прав (как раз через `ActivityCompat.requestPermissions(Activity, String[], int)`).
3. Результат запроса на получение прав прилетает в вызове метода `ActivityCompat.onRequestPermissionsResult`, в котором запускается activity камеры, если права были получены, иначе ничего не делается.

В самом файле есть более детальное описание. В эту сторону, думаю, нужно посмотреть.

2023-03-18 13:05 UTC, Vladislav0Art commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        circleOptions.fillColor(0x30ff0000);
Лучше в константу вынести, название которой бы отражало этот цвет. Например, `TRANSLUCENT_RED = 0x30ff0000`.

2023-03-18 22:41 UTC, Vladislav0Art commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +            enableMyLocation();
Данный `while` будет постоянно выполнять код своего тела (попробовал на `println`). Решаем проблему.

2023-03-19 14:00 UTC, vvselischev commented on app/src/main/java/com/gigachadllc/enchanted_towers/MapsActivity.java
> +        circleOptions.fillColor(0x30ff0000);
Мне кажется, это уже должно быть реализовано где-то. Конвертер из enum-а цветов в 16-ричное представление (но не уверен).

2023-03-19 18:36 UTC, Vladislav0Art commented
В последнем коммите указал, какой сейчас workflow по получению прав к геолокации и показу карты. Дублирую тут:

### Currenlty we have the following flow:
1. If **all** location permissions already granted -> mount google map.
2. If **any** permission absents, **either**:
    1. Show rationale with info why permissions needed (_this applies depending on OS version_):
        1. If user **accepts** dialog -> show permissions grant panel.
        2. If user **rejects** dialog  -> limit content (do not mount google map).
    2. Directly show permissions grant panel.
3. **Resulting permissions:**
    1. **At least** coarse location permission granted -> mount google map.
    2. **No** location permissions -> limit content (do not mount google map).

В случае, если пользователь дал права только на `coarse location`, то при каждом заходе мы будет просить права на точное местоположение (`fine location`), т.к. `coarse location` довольно [неточный](https://developer.android.com/training/location/permissions#accuracy).

2023-04-07 13:20 UTC, dmitrii-artuhov commented on client/app/src/main/java/enchantedtowers/client/MainActivity.java
> +    //Fragment fragment = new MapFragment();
Если комментарий не нужен, то удалить

2023-04-07 13:24 UTC, dmitrii-artuhov commented on client/app/src/main/java/enchantedtowers/client/MapActivity.java
> +                    Boolean fineLocationPermissionGranted = result.getOrDefault(
почему просто на написать в этоме месте `boolean` вместо обертки?

2023-04-07 13:30 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/MainActivity.java
> +    //Fragment fragment = new MapFragment();
done

2023-04-07 13:31 UTC, dmitrii-artuhov commented on client/app/src/main/java/enchantedtowers/client/MapActivity.java
> +        /*if (PermissionManager.checkLocationPermission(this)) {
Удалить комментарий, если не нужен

2023-04-07 13:31 UTC, dmitrii-artuhov commented on client/app/src/main/java/enchantedtowers/client/MapFragment.java
> +    // TODO: make the following fields Optional<T>
Надо сделать

2023-04-07 13:31 UTC, dmitrii-artuhov commented on client/app/src/main/res/layout/activity_map.xml
> +    <!--    <com.google.android.gms.maps.MapView-->
Удалить комментарий

2023-04-07 13:34 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/MapActivity.java
> +                    Boolean fineLocationPermissionGranted = result.getOrDefault(
Добавил TODO

2023-04-07 13:47 UTC, Vladislav0Art commented on client/app/src/main/java/enchantedtowers/client/MapFragment.java
> +    // TODO: make the following fields Optional<T>
Потом

2023-04-07 13:48 UTC, merged